services:
  - type: web
    name: whatsapp-backend
    env: node
    plan: free
    buildCommand: pnpm install --no-frozen-lockfile
    startCommand: pnpm start
    envVars:
      # App Port
      - key: PORT
        value: 3000

      # OpenAI
      - key: OPENAI_API_KEY
        sync: false

      # WhatsApp Cloud API
      - key: WHATSAPP_VERIFY_TOKEN
        sync: false
      - key: WHATSAPP_PHONE_ID
        sync: false
      - key: WHATSAPP_TOKEN
        sync: false

      # Database (linked below)
      - key: DATABASE_URL
        fromDatabase:
          name: whatsapp-prod-db
          property: connectionString

      # JWT
      - key: JWT_SECRET
        sync: false

      # Cloudinary
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

databases:
  - name: whatsapp-prod-db
    plan: free
